Demo: error handling & loading
onflow/fcl-dev-wallet pull request #155
Opened 2022-10-03 20:01 UTC by bartolomej

2022-10-11 23:40 UTC, huyndo requested changes
Thanks a lot @bartolomej for the PR! Everything looks good for me. I just got some suggestions before we merge:

1. Adding text wrap to the error message. I added the below to [styles/globals.css](https://github.com/onflow/fcl-dev-wallet/blob/a409ad0832bee2f224a52bfad23c2b898339dd5d/styles/globals.css) and it works pretty well. Lmk what you think. (Got it from [here](https://stackoverflow.com/questions/248011/how-do-i-wrap-text-in-a-pre-tag))
```
pre {
  white-space: pre-wrap;       /* Since CSS 2.1 */
  white-space: -moz-pre-wrap;  /* Mozilla, since 1999 */
  white-space: -pre-wrap;      /* Opera 4-6 */
  white-space: -o-pre-wrap;    /* Opera 7 */
  word-wrap: break-word;       /* Internet Explorer 5.5+ */
}
```
2. `title` param for `Err`. I added those as suggestions just to give more clarity on the error.
3. Removing `spinners-react` dependency. There's this code [snippet](https://gist.github.com/knowbody/578b35164b69e867ed4913423f6bed30) which gives a spinner using `styled-components` (which is already a dependency). You might encounter a certain error when trying it out, the solution can be found [here](https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam).

Those are just my suggestions on the PR. Feel free to say what you think is suitable/not suitable. Thanks for contributing!

2022-10-11 23:40 UTC, huyndo commented on src/comps/err.comp.tsx
> +export function Err({error}: {error: Error}) {
```suggestion
export function Err({error, title="Error occurred"}: {error: Error, title?: string}) {
```

2022-10-11 23:40 UTC, huyndo commented on src/comps/err.comp.tsx
> +      <Themed.h1 sx={{textAlign: "center", mb: 20}}>Error occurred</Themed.h1>
```suggestion
      <Themed.h1 sx={{textAlign: "center", mb: 20}}>{title}</Themed.h1>
```

2022-10-11 23:40 UTC, huyndo commented on pages/fcl/authn.tsx
> +  if (error) return <Err error={error} />
```suggestion
  if (error) return <Err error={error} title="Authentication error"/>
```

2022-10-11 23:40 UTC, huyndo commented on contexts/AuthnContext.tsx
> +  if (error) return <Err error={error} />
```suggestion
  if (error) return <Err error={error} title="Initialization Error"/>
```

2022-10-12 08:45 UTC, bartolomej commented
@huyndo Awesome! I think that makes sense! Added fixes for 2. and 3. suggestions.

For the text wrapping issue (1.) you mentioned that you already added this to the `globals.css`, but I can't see that in the [mentioned commit](https://github.com/onflow/fcl-dev-wallet/blob/a409ad0832bee2f224a52bfad23c2b898339dd5d/styles/globals.css). Should I add this on this branch?

2022-10-12 14:02 UTC, sideninja approved these changes

2022-10-12 16:18 UTC, huyndo approved these changes
Looks good to me @bartolomej. Thanks a lot!

2022-10-12 16:40 UTC, merged

2022-10-12 16:41 UTC, gregsantos commented
Thanks for this great addition @bartolomej !